apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: guestbook
  namespace: argocd
  labels:
    name: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/Alex77728777/github-workflows-argocd.git
    targetRevision: main
    path: kustomization
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
